import matplotlib.pyplot as plt
import pandas as pd
from analise_noticias import analisar_empresa

def graficos(id_empresa):
    analisar_empresa(id_empresa)
    noticias = pd.read_csv(f"analises_csv/analise{id_empresa}.csv")

    print(f"Empresa {id_empresa}\n")

    corr_dia_PRE = noticias["sentimento_PRE"].corr(noticias["varia_dia"])
    plt.scatter(noticias["sentimento_PRE"], noticias["varia_dia"])
    plt.xlabel("Sentimento_PRE")
    plt.ylabel("Variação - No Dia")
    plt.title("Sentimento_PRE x Variação - No Dia")
    plt.grid(True)
    plt.savefig(f"graficos/{id_empresa}-PRE_x_Varia_Dia_0.png", dpi=300, bbox_inches="tight")
    plt.close()

    corr_dia_POS = noticias["sentimento_POS"].corr(noticias["varia_dia"])
    plt.scatter(noticias["sentimento_POS"], noticias["varia_dia"])
    plt.xlabel("Sentimento_POS")
    plt.ylabel("Variação - No Dia")
    plt.title("Sentimento_POS x Variação - No Dia")
    plt.grid(True)
    plt.savefig(f"graficos/{id_empresa}-POS_x_Varia_Dia_0.png", dpi=300, bbox_inches="tight")
    plt.close()

    corr_1_dia_a_PRE = noticias["sentimento_PRE"].corr(noticias["varia_1_dia_antes"])
    plt.scatter(noticias["sentimento_PRE"], noticias["varia_1_dia_antes"])
    plt.xlabel("Sentimento_PRE")
    plt.ylabel("Variação - 1 Dia Antes")
    plt.title(f"Sentimento_PRE x Variação - 1 Dia Antes")
    plt.grid(True)
    plt.savefig(f"graficos/{id_empresa}-PRE_x_Varia_Dia_1_Antes.png", dpi=300, bbox_inches="tight")
    plt.close()

    corr_1_dia_a_POS = noticias["sentimento_POS"].corr(noticias["varia_1_dia_antes"])
    plt.scatter(noticias["sentimento_POS"], noticias["varia_1_dia_antes"])
    plt.xlabel("Sentimento_POS")
    plt.ylabel("Variação - 1 Dia Antes")
    plt.title("Sentimento_POS x Variação - 1 Dia Antes")
    plt.grid(True)
    plt.savefig(f"graficos/{id_empresa}-POS_x_Varia_Dia_1_Antes.png", dpi=300, bbox_inches="tight")
    plt.close()

    corr_1_dia_d_PRE = noticias["sentimento_PRE"].corr(noticias["varia_1_dia_depois"])
    plt.scatter(noticias["sentimento_PRE"], noticias["varia_1_dia_depois"])
    plt.xlabel("Sentimento_PRE")
    plt.ylabel("Variação - 1 Dia Depois")
    plt.title("Sentimento_PRE x Variação - 1 Dia Depois")
    plt.grid(True)
    plt.savefig(f"graficos/{id_empresa}-PRE_x_Varia_Dia_1_Depois.png", dpi=300, bbox_inches="tight")
    plt.close()

    corr_1_dia_d_POS = noticias["sentimento_POS"].corr(noticias["varia_1_dia_depois"])
    plt.scatter(noticias["sentimento_POS"], noticias["varia_1_dia_depois"])
    plt.xlabel("Sentimento_POS")
    plt.ylabel("Variação - 1 Dia Depois")
    plt.title("Sentimento_POS x Variação - 1 Dia Depois")
    plt.grid(True)
    plt.savefig(f"graficos/{id_empresa}-POS_x_Varia_Dia_1_Depois.png", dpi=300, bbox_inches="tight")
    plt.close()

    corr_2_dia_a_PRE = noticias["sentimento_PRE"].corr(noticias["varia_2_dias_antes"])
    plt.scatter(noticias["sentimento_PRE"], noticias["varia_2_dias_antes"])
    plt.xlabel("Sentimento_PRE")
    plt.ylabel("Variação - 2 Dias Antes")
    plt.title("Sentimento_PRE x Variação - 2 Dias Antes")
    plt.grid(True)
    plt.savefig(f"graficos/{id_empresa}-PRE_x_Varia_Dia_2_Antes.png", dpi=300, bbox_inches="tight")
    plt.close()

    corr_2_dia_a_POS = noticias["sentimento_POS"].corr(noticias["varia_2_dias_antes"])
    plt.scatter(noticias["sentimento_POS"], noticias["varia_2_dias_antes"])
    plt.xlabel("Sentimento_POS")
    plt.ylabel("Variação - 2 Dias Antes")
    plt.title("Sentimento_POS x Variação - 2 Dias Antes")
    plt.grid(True)
    plt.savefig(f"graficos/{id_empresa}-POS_x_Varia_Dia_2_Antes.png", dpi=300, bbox_inches="tight")
    plt.close()

    corr_2_dia_d_PRE = noticias["sentimento_PRE"].corr(noticias["varia_2_dias_depois"])
    plt.scatter(noticias["sentimento_PRE"], noticias["varia_2_dias_depois"])
    plt.xlabel("Sentimento_PRE")
    plt.ylabel("Variação - 2 Dias Depois")
    plt.title("Sentimento_PRE x Variação - 2 Dias Depois")
    plt.grid(True)
    plt.savefig(f"graficos/{id_empresa}-PRE_x_Varia_Dia_2_Depois.png", dpi=300, bbox_inches="tight")
    plt.close()

    corr_2_dia_d_POS = noticias["sentimento_POS"].corr(noticias["varia_2_dias_depois"])
    plt.scatter(noticias["sentimento_POS"], noticias["varia_2_dias_depois"])
    plt.xlabel("Sentimento_POS")
    plt.ylabel("Variação - 2 Dias Depois")
    plt.title("Sentimento_POS x Variação - 2 Dias Depois")
    plt.grid(True)
    plt.savefig(f"graficos/{id_empresa}-POS_x_Varia_Dia_2_Depois.png", dpi=300, bbox_inches="tight")
    plt.close()

    with open(f"correlacoes_txt/correlacao_{id_empresa}.txt", "w") as arq:
        arq.write(f"Dia Atual:\n\tPRE: {corr_dia_PRE}\n\tPOS: {corr_dia_POS}\n\n")
        arq.write(f"Dia 1 antes:\n\tPRE: {corr_1_dia_a_PRE}\n\tPOS: {corr_1_dia_a_POS}\n\n")
        arq.write(f"Dia 1 depois:\n\tPRE: {corr_1_dia_d_PRE}\n\tPOS: {corr_1_dia_d_POS}\n\n")
        arq.write(f"Dia 2 antes:\n\tPRE: {corr_2_dia_a_PRE}\n\tPOS: {corr_2_dia_a_POS}\n\n")
        arq.write(f"Dia 2 depois:\n\tPRE: {corr_2_dia_d_PRE}\n\tPOS: {corr_2_dia_d_POS}\n\n")

print("Graficos: \n")
for id in ["CMIG4", "CPLE6", "SBSP3"]:
    graficos(id)